name: WayAlgorithm
version: '2.2.1'
main: org.algorithm.wayAlgorithm.WayAlgorithm
api-version: '1.20'
author: LacyCat
description: A* algorithm simulator
commands:
  set1:
    description: Start Point
    usage: /set1 <x> <y> <z>
  set2:
    description: End Point
    usage: /set2 <x> <y> <z>
  calc:
    description: Calculate the Shortest route
    usage: /calc
  reset:
    description: Kill all Path armor
    usage: /reset